import fs from 'node:fs';
import {researchFeature,researchBody,researchTitle,researchDescription} from './opex-research.mjs';
import path from 'node:path';
import {projects,fields,articles} from './data.mjs';
import {rootsBody} from './nigerian-roots.mjs';
import {home} from './home-v3.mjs';
import {heliosCinema} from './helios.mjs';
import {capitalBody,partnershipEnquiries,capitalPhotography} from './capital.mjs';
import {addPageVisual} from './page-visuals.mjs';
import {updates,newsroomNav,updateList,newsroomTopics} from './news.mjs';
const origin=(process.env.SITE_URL||'https://terranile.com').replace(/\/$/,'');
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const mark='<img class="brand-art" src="/assets/terranile-logo-clean.png" alt="" width="240" height="68" aria-hidden="true">';
const brand=`<a class="brand" href="/" aria-label="Terranile home">${mark}</a>`;
const navigation=[['Capital','/capital/'],['Research','/research/'],['Projects','/projects/'],['Company','/company/'],['News','/news/']];
function header(route){const links=navigation.map(([name,url])=>`<a href="${url}" ${route.startsWith(url)?'aria-current="page"':''}>${name}</a>`).join('');return `<a class="skip" href="#main">Skip to content</a><header class="header">${brand}<nav class="nav" aria-label="Main navigation">${links}<a class="contact-link" href="/contact/">Contact</a></nav><button class="menu-button" type="button" aria-expanded="false" aria-controls="mobile-navigation">Menu</button><nav class="mobile-nav" id="mobile-navigation" aria-label="Mobile navigation">${links}<a href="/contact/">Contact</a></nav></header>`}
function footer(){const footerName='<a class="brand footer-name" href="/" aria-label="Terranile home">terranile</a>';return `<footer class="footer"><div class="footer-top"><div>${footerName}<p class="footer-tagline">Build infrastructure.<br>Build intelligence.<br>Build what lasts.</p></div><div class="footer-links"><div><span class="mono">Our work</span><a href="/companies/avan/">AVAN</a><a href="/companies/avanbnb/">AvanBnB</a><a href="/research/helios/">Project Helios</a><a href="/projects/opex-intelli/">OPEX Intelli</a></div><div><span class="mono">Terranile</span><a href="/company/">Company</a><a href="/nigerian-roots/">Our Nigerian roots</a><a href="/research/">Research</a><a href="/news/">Newsroom</a><a href="/perspectives/">Perspectives</a><a href="/announcements/">Announcements</a><a href="/projects/real-assets/">Real estate partnerships</a></div><div><span class="mono">Connect</span><a href="/contact/">Contact</a><a href="/careers/">Careers</a><a href="/legal/">Legal</a><a href="/legal/#privacy">Privacy</a></div></div></div><div class="footer-word" aria-hidden="true">terranile</div><div class="footer-bottom"><span>© 2025–${new Date().getFullYear()} Terranile Digital Infrastructure Ltd.</span><span>Originating in Nigeria. Built for global relevance.</span></div></footer>`}
function shell(route,title,description,body){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f4f4f1"><title>${esc(title)} — Terranile</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${origin}${route}"><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)} — Terranile"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${origin}${route}"><link rel="icon" type="image/png" sizes="64x64" href="/assets/favicon-light.png" media="(prefers-color-scheme: light)"><link rel="icon" type="image/png" sizes="64x64" href="/assets/favicon-dark.png" media="(prefers-color-scheme: dark)"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link rel="stylesheet" href="/site.css"><link rel="stylesheet" href="/visuals-v2.css"><link rel="stylesheet" href="/visuals-v3.css"><link rel="stylesheet" href="/brand.css"><link rel="stylesheet" href="/research.css"><script src="/site.js" defer></script><script src="/panel-deck.js" defer></script></head><body class="${route==='/research/helios/'?'helios-detail':''}">${header(route)}<main id="main">${body}</main>${footer()}</body></html>`}
function write(route,title,description,body){body=addPageVisual(route,body);const dest=path.join('dist',route,'index.html');fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,shell(route,title,description,body).replace('</head>','<script src="/city-film.js" defer></script></head>'));return route}
function initiativeLogo(p){const logos={avanbnb:'avanbnb-logo-clean.png',avan:'avan-logo-clean.png',helios:'helios-logo-clean.png','opex-intelli':'opex-logo-clean.png'};return logos[p.slug]?`<div class="initiative-brand"><img class="initiative-logo initiative-logo--${p.slug}" src="/assets/${logos[p.slug]}" alt="${p.name} logo" width="160" height="120"></div>`:''}
function canvas(p){return `<canvas data-scene="${p.slug==='helios'?'helios':'opex'}" role="img" aria-label="${p.slug==='helios'?'Conceptual visualization of connected scientific information; not research data':'Illustrative quantitative signal lines; not market data'}"></canvas>`}
function imageMarkup(p,eager=false){return `<img src="/assets/${p.image}" alt="${p.alt}" ${eager?'fetchpriority="high"':'loading="lazy"'} width="1672" height="941">`}
function media(p,extra=''){return `<a class="project-media ${p.slug==='helios'?'helios-media':p.slug==='opex-intelli'?'opex-media':''} ${extra}" href="${p.path}" aria-label="Explore ${p.name}">${p.image?imageMarkup(p):canvas(p)}${p.slug==='helios'?'<span class="scientific-meta mono">Helios / Biomedical intelligence<br>Conceptual biological study</span>':''}<div class="media-heading"><strong>${p.name}</strong><span class="pill">${p.category}</span></div></a>`}
function project(p){return `<article class="project reveal">${media(p)}<div class="project-caption"><h3>${p.slug==='avan'?'Trust is infrastructure.':p.slug==='helios'?'Intelligence for research.':p.slug==='avanbnb'?'A better foundation for every stay.':'Research before conviction.'}</h3><p>${p.slug==='avan'?'Property verification, bank-held escrow and accountable workflows. The systems around a transaction.':p.intro}</p><div class="project-links"><a class="text-link" href="${p.path}">Explore ${p.name}</a>${p.website?`<a class="text-link external-link" href="${p.website}" target="_blank" rel="noopener noreferrer">Visit ${p.name}</a>`:''}</div></div></article>`}
function pageHero(label,title,lead,meta=''){return `<section class="page-hero"><div class="breadcrumbs"><a href="/">Terranile</a> / ${label}</div><span class="eyebrow">${label}</span><h1>${title}</h1><p class="page-lead">${lead}</p>${meta?`<div class="page-meta mono">${meta}</div>`:''}</section>`}
function editorial(){return `<div class="editorial-list">${articles.map(a=>`<a class="editorial-row" href="/perspectives/${a.slug}/"><span class="mono">${a.category}</span><h3>${a.title}</h3><span>Read perspective</span></a>`).join('')}</div>`}
const routes=[];
routes.push(write('/research/opex-001/',researchTitle,researchDescription,researchBody()));
routes.push(write('/nigerian-roots/','Our Nigerian roots','Originating in Nigeria, with an African outlook and a long-term ambition to build lasting infrastructure.',`${pageHero('Our Nigerian roots','Nigerian roots.<br>African outlook.','Our work begins in Nigeria, with the ambition to build systems that have relevance across Africa and beyond.')}${rootsBody}`));
routes.push(write('/capital/','Capital & investment','Connecting capital with technology, infrastructure and real opportunities across African markets.',`${pageHero('Capital & investment','Capital for what<br>Africa builds next.','Building the systems and relationships that connect opportunity with capital.')}${capitalBody}${capitalPhotography}`));
routes.push(write('/','Build what lasts.','Terranile builds technology and infrastructure across real estate, intelligence, scientific research, capital and the physical world.',home({projects,project,fields,editorial})));
for(const p of projects){const next=projects.find(n=>n.slug===p.next);routes.push(write(p.path,p.name,p.intro,`${pageHero(p.category,p.heading,p.intro,`<span>${p.name}</span><span>${p.status}</span>`)}${initiativeLogo(p)}${p.website?`<div class="section project-website"><a class="pill-link" href="${p.website}" target="_blank" rel="noopener noreferrer">Visit ${p.name}</a><span class="mono">${new URL(p.website).hostname}</span></div>`:''}<div class="visual detail-visual ${p.slug==='helios'?'helios-media':p.slug==='opex-intelli'?'opex-media':''}">${p.image?`<img src="/assets/${p.image}" alt="${p.alt}" width="1600" height="1000" fetchpriority="high">`:canvas(p)}${!p.image?'<span class="scientific-meta mono">Terranile / Conceptual systems study</span>':''}</div><section class="section content-grid"><span class="eyebrow">Approach</span><div><h2>${p.statement}</h2><p>${p.body}</p><div class="capabilities">${p.capabilities.map(([title,copy])=>`<div><h3>${title}</h3><p>${copy}</p></div>`).join('')}</div><p class="note">${p.note}</p>${p.slug==='helios'?heliosCinema():''}</div></section>${p.slug==='opex-intelli'?`<section class="section"><span class="eyebrow">Research</span><p>OPEX Intelli develops and evaluates quantitative systems through historical market research.</p>${researchFeature()}</section>`:''}<section class="next-project"><div><span class="eyebrow">Continue exploring</span><h2>${next.name}</h2></div><a class="text-link" href="${next.path}">Explore ${next.name}</a></section>`))}
// Preserve the original portfolio route while preparing Terranile's /avan/ address.
fs.mkdirSync('dist/companies/avan',{recursive:true});
fs.copyFileSync('dist/avan/index.html','dist/companies/avan/index.html');
function index(title,lead,list){return `${pageHero(title,title,lead)}<section class="section project-index">${list.map(p=>`<article>${p.image?`<a href="${p.path}" aria-label="Explore ${p.name}"><img class="index-image" src="/assets/${p.image}" alt="${p.alt}" width="1672" height="941" loading="lazy"></a>`:''}<span class="mono">${p.category} / ${p.status}</span><h2>${p.name}</h2><p>${p.intro}</p><a class="text-link" href="${p.path}">Explore ${p.name}</a></article>`).join('')}</section>`}
// Preserve old bookmarks while removing the Companies overview.
fs.mkdirSync('dist/companies',{recursive:true});
fs.writeFileSync('dist/companies/index.html',shell('/companies/','Explore projects','Explore Terranile projects.','<section class="page-hero"><h1>Explore our projects.</h1><a class="text-link" href="/projects/">All projects</a></section>').replace('</head>','<meta http-equiv="refresh" content="0;url=/projects/"></head>'));
routes.push(write('/research/','Research','Terranile’s biomedical and quantitative research initiatives.',index('Research','Long-term questions. Computational methods. Room to experiment.',[projects[1],projects[3]]).replace('<section class="section project-index">',`<section class="section">${researchFeature()}</section><section class="section project-index">`)));
routes.push(write('/projects/','Projects','Explore Terranile’s quantitative intelligence, real assets and infrastructure projects.',index('Projects','From computational research to the physical world.',projects)));
routes.push(write('/company/','Company','Terranile Digital Infrastructure Ltd. builds companies, systems and research initiatives for the long term.',`${pageHero('Company','Build infrastructure.<br>Build intelligence.<br>Build what lasts.','Founded in 2025, Terranile Digital Infrastructure Ltd. is the parent company behind a growing portfolio of technology, infrastructure, real-estate, financial infrastructure and scientific research initiatives.')}<section class="section content-grid"><span class="eyebrow">Our purpose</span><div><h2>Originating in Nigeria.<br>Designed for global relevance.</h2><p>Terranile exists to build infrastructure for problems that require more than another lightweight consumer application. We create and develop companies, research projects and systems internally, with a long-term view of their role in the world.</p><p>Our work considers how capital moves, how property is transacted, how investment connects to partner-led real assets and how computational systems help researchers process scientific information.</p></div></section><section class="section fields"><div class="section-head"><div><span class="eyebrow">Approach</span><h2>Understand deeply.<br>Build deliberately.</h2></div></div><div class="capabilities">${[['Start with the underlying system','Examine the documentation, incentives, controls and information that a problem depends on.'],['Build within a shared structure','Develop distinct initiatives while retaining a consistent long-term approach.'],['Connect digital and physical','Consider the relationship between software, capital, assets and the people who use them.'],['Leave room for research','Pursue scientific and experimental questions alongside commercial development.']].map(([t,c])=>`<div><h3>${t}</h3><p>${c}</p></div>`).join('')}</div></section><section class="section"><div class="section-head"><div><span class="eyebrow">Companies & projects</span><h2>A portfolio of systems.</h2></div></div><div class="project-index">${projects.map(p=>`<article><span class="mono">${p.category}</span><h2>${p.name}</h2><p>${p.summary}</p><a class="text-link" href="${p.path}">Explore initiative</a></article>`).join('')}</div></section><section class="section content-grid"><span class="eyebrow">Leadership</span><div><h2>Built on accountable work.</h2><p>Leadership profiles will be published here as approved company information becomes available.</p><a class="text-link" href="/contact/">Contact Terranile</a></div></section>`));
routes.push(write('/perspectives/','Perspectives','Explore the principles behind Terranile’s infrastructure and research initiatives.',`${pageHero('Perspectives','How we think.','Notes on the systems, questions and principles behind our work.')}<section class="section">${newsroomNav('/perspectives/')}${editorial()}</section>`));
for(const [route,title,type,lead] of [['/news/','News','news','Company news, milestones and updates from across Terranile.'],['/announcements/','Announcements','announcement','Official partnerships, research releases, product launches and company updates.']])routes.push(write(route,title,lead,`${pageHero(title,title+'.',lead)}<section class="section">${newsroomNav(route)}${newsroomTopics}${updateList(type)}</section>`));
for(const update of updates.filter(item=>item.status==='published'))routes.push(write(`/news/${update.slug}/`,update.title,update.summary,`${pageHero(update.topic,esc(update.title),esc(update.summary),`<time datetime="${esc(update.date)}">${esc(update.date)}</time>`)}<article class="section content-grid"><span class="eyebrow">${update.type==='announcement'?'Announcement':'News'}</span><div>${update.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')}<a class="text-link" href="/news/">Back to the newsroom</a></div></article>`));
for(const a of articles)routes.push(write(`/perspectives/${a.slug}/`,a.title,a.lead,`${pageHero(a.category,a.title,a.lead,'<span>Terranile perspective</span>')}<article class="section content-grid"><span class="eyebrow">Perspective</span><div>${a.paragraphs.map(p=>`<p>${p}</p>`).join('')}<p class="note">This overview describes Terranile’s direction. It is not an announcement of completed projects or published research.</p><a class="text-link" href="/perspectives/">All perspectives</a></div></article>`));
routes.push(write('/contact/','Contact','Contact and partnership information for Terranile Digital Infrastructure Ltd.',`${pageHero('Contact','Start with<br>a shared problem.','Terranile’s work brings together technology, research, transaction infrastructure and real-estate partnerships.')}<section class="section content-grid"><span class="eyebrow">Working together</span><div><h2>Ideas with a long horizon.</h2><div class="capabilities"><div><h3>Infrastructure & partnerships</h3><p>For organizations working on transaction systems, property verification, financial infrastructure or investment connections.</p></div><div><h3>Research collaboration</h3><p>For researchers exploring biomedical information, computational systems and scientific relationships.</p></div><div><h3>Real estate partnerships</h3><p>For developers, landowners and industry partners exploring technology, distribution, market access and transaction infrastructure.</p></div><div><h3>Company enquiries</h3><p>For company information, press enquiries and future opportunities.</p></div></div><p class="note">Terranile’s verified public contact details will be published here when available.</p></div></section>`));
routes.push(write('/careers/','Careers','Future opportunities to work on Terranile’s technology, infrastructure and research initiatives.',`${pageHero('Careers','Work on<br>what lasts.','Terranile’s work spans engineering, research, transaction infrastructure and the physical world.')}<section class="section content-grid"><span class="eyebrow">Opportunities</span><div><h2>Building the foundations.</h2><p>Approved roles and application details will be published here when available. No vacancies are advertised on this website at present.</p><a class="text-link" href="/company/">Learn about Terranile</a></div></section>`));
routes.push(write('/legal/','Legal & privacy','Website information, privacy and visual credits for the Terranile website.',`${pageHero('Legal','Website information.','Information about this website and the initiatives it describes.')}<section class="section legal-copy"><h2>Company and project information</h2><p>This website introduces Terranile Digital Infrastructure Ltd. and its developing companies, projects and research directions. It does not constitute an offer of investment, property or financial services.</p><p>Capabilities described here may be in development or exploratory. No completed developments, published research, investment performance or clinical validation is claimed unless explicitly stated.</p><h2 id="privacy">Privacy</h2><p>This version of the website includes no contact form, account system, advertising trackers or analytics scripts. It does not ask visitors to submit personal information. Hosting services may process technical request information required to deliver the website.</p><p>Fonts are served by Google Fonts. Loading those fonts sends a request to Google’s font services. You can learn about their handling of these requests in <a class="text-link" href="https://developers.google.com/fonts/faq/privacy">Google Fonts’ privacy information</a>.</p><h2>Scientific and quantitative visuals</h2><p>Computational visuals are conceptual illustrations. They do not represent Helios research results or actual biological measurements. OPEX Research 001 separately presents historical simulated market results, with qualifications shown alongside its figures.</p><h2>Photography</h2><p>Architectural photography is illustrative and does not represent Terranile-owned or completed developments. Source credits are available in the site’s asset documentation.</p></section>`));
fs.writeFileSync('dist/contact/index.html',fs.readFileSync('dist/contact/index.html','utf8').replace('</main>',partnershipEnquiries+'</main>'));
// Contact details are supplied and approved by the company owner.
const contactFile='dist/contact/index.html';
fs.writeFileSync(contactFile,fs.readFileSync(contactFile,'utf8').replace('<p class="note">Terranile’s verified public contact details will be published here when available.</p>','<p class="mono">Company enquiries & partnerships</p><a class="contact-email" href="mailto:info@terranile.com">info@terranile.com</a><p>Tell us about the problem, the context and where you see an opportunity to work together.</p>'));
const legalFile='dist/legal/index.html';
// Original generated visual studies and real film credits are distinct from company facts.
fs.writeFileSync(legalFile,fs.readFileSync(legalFile,'utf8').replace('Source credits are available in the site’s asset documentation.','Architecture: <a class="text-link" href="https://unsplash.com/photos/a-black-and-white-photo-of-a-building-qJKUR2PLxMQ">Joss Broward</a>. Hospitality: <a class="text-link" href="https://unsplash.com/photos/a-neutral-toned-living-room-with-modern-decor-KJVfcwpHI1w">Franco Debartolo</a>. Used under the <a class="text-link" href="https://unsplash.com/license">Unsplash License</a>.'));
fs.writeFileSync(legalFile,fs.readFileSync(legalFile,'utf8').replace('<h2>Photography</h2>','<h2>Generated visual studies</h2><p>The waterfront hero, AVAN courtyard, Helios biological artwork, OPEX workspace and people scenes are original AI-generated concepts. They illustrate Terranile’s areas of work and do not depict completed developments, company facilities, actual staff or experimental findings.</p><h2>Laboratory films</h2><p>Illustrative laboratory films by <a class="text-link" href="https://www.pexels.com/video/a-scientist-looking-through-a-microscope-9373403/">Mikhail Nilov</a> and <a class="text-link" href="https://www.pexels.com/video/close-up-shot-of-a-petri-dish-7705448/">Andrey Kirievskiy</a>, used under the <a class="text-link" href="https://www.pexels.com/license/">Pexels License</a>. These are stock research settings, not Terranile facilities.</p><h2>Photography</h2>'));
fs.writeFileSync(legalFile,fs.readFileSync(legalFile,'utf8').replace('<h2>Photography</h2>','<h2>Lagos aerial film</h2><p>Lagos aerial film by <a class="text-link" href="https://www.pexels.com/video/aerial-view-of-lagos-cityscape-over-lagoon-29103989/">Vitalis Nwenyi</a>, used under the Pexels License. This is real footage of Lagos, not a Terranile development.</p><h2>Independence Day film</h2><p>Nigeria celebration footage from <a class="text-link" href="https://www.pexels.com/video/a-man-and-a-woman-holding-a-miniature-flag-of-nigera-8779559/">Pexels clip 8779559</a>, used under the Pexels License. The people depicted are stock performers, not Terranile staff or endorsers.</p><h2>Real city and infrastructure photography</h2><p>Abuja photography by <a class="text-link" href="https://www.pexels.com/photo/aerial-view-of-abuja-in-fog-nigeria-16237804/">Stuffedbox NG</a> under the Pexels License. Lagos photography by <a class="text-link" href="https://unsplash.com/photos/the-sun-is-setting-behind-a-tall-building-yLkbhB8gyWE">Emmanuel Ikwuegbu</a> under the Unsplash License. Nairobi photography from <a class="text-link" href="https://www.pexels.com/photo/skyline-view-of-nairobi-cityscape-at-daytime-29069344/">Pexels</a> and <a class="text-link" href="https://www.pexels.com/photo/view-of-a-city-26898331/">Kelvin Kibe</a>. Data-centre photography by <a class="text-link" href="https://www.pexels.com/photo/server-racks-on-data-center-4508751/">Brett Sayles</a>. Pexels photographs are used under the Pexels License. These images illustrate regions and areas of work; they do not depict Terranile-owned assets or facilities.</p><h2>Photography</h2>'));
fs.writeFileSync('dist/404.html',shell('/404/','Page not found','The requested page could not be found.',`${pageHero('404','A different direction.','The page you’re looking for could not be found.')}<section class="section"><a class="text-link" href="/">Return to Terranile</a></section>`));
fs.writeFileSync('dist/robots.txt',`User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`);
fs.writeFileSync('dist/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${routes.map(r=>`<url><loc>${origin}${r}</loc></url>`).join('')}</urlset>`);
fs.writeFileSync('dist/_headers','/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  Permissions-Policy: camera=(), microphone=(), geolocation=()\n');
console.log(`Built ${routes.length} routes and 404 page.`);
