const clips=[
{file:'helios-lab',title:'At the bench.',label:'Microscope / 23 sec',copy:'Observation. Evidence. A closer examination.',author:'Mikhail Nilov / Pexels',source:'https://www.pexels.com/video/a-scientist-looking-through-a-microscope-9373403/'},
{file:'helios-sample',title:'Start with the sample.',label:'Sample study / 14 sec',copy:'Small observations. Wider research questions.',author:'Andrey Kirievskiy / Pexels',source:'https://www.pexels.com/video/close-up-shot-of-a-petri-dish-7705448/'}
];
export function heliosCinema(){return `<section class="helios-experience">
<span class="eyebrow">Inside the biological world</span>
<div class="microscopy-cinema" id="helios-cinema"><img class="cinema-poster" src="/assets/helios-microscopy.webp" alt="Conceptual microscopic cell structures with teal membranes and coral interiors" loading="lazy" width="1672" height="941"><div class="cinema-caption"><span class="mono">Helios / Biological systems</span><h3>Complexity, at a different scale.</h3><p>A microscopy-inspired visual study of structure and connection.</p></div><button class="cinema-pause" type="button" data-motion-toggle aria-pressed="false">Pause motion</button></div>
<p class="cinema-credit">Generated conceptual artwork. It does not represent laboratory results or a Terranile research facility.</p>
<div class="microscopy-cinema lab-cinema" id="helios-laboratory"><video data-loop-video data-src="/assets/helios-lab.mp4" poster="/assets/helios-lab-poster.jpg" preload="none" muted loop playsinline aria-hidden="true"></video><div class="cinema-caption"><span class="mono">Research in practice / Illustrative footage</span><h3 data-film-title>At the bench.</h3><p data-film-description>Observation. Evidence. A closer examination.</p></div><button class="cinema-pause" type="button" data-motion-toggle aria-pressed="false">Pause video</button></div>
<div class="cinema-controls" role="group" aria-label="Choose laboratory film">${clips.map((clip,i)=>`<button type="button" aria-pressed="${i===0?'true':'false'}" aria-controls="helios-laboratory" data-film-select data-film-src="/assets/${clip.file}.mp4" data-film-poster="/assets/${clip.file}-poster.jpg" data-film-title="${clip.title}" data-film-description="${clip.copy}" data-film-author="${clip.author}" data-film-source="${clip.source}">${clip.label}</button>`).join('')}</div>
<p class="cinema-credit">Illustrative laboratory footage by <a class="text-link" data-film-credit href="${clips[0].source}">${clips[0].author}</a>, used under the <a class="text-link" href="https://www.pexels.com/license/">Pexels License</a>. This is not a Terranile facility.</p>
</section>`}
