import {ecosystem} from './ecosystem.mjs';
import {capitalIntro} from './capital.mjs';
export function home({projects}){
const find=slug=>projects.find(p=>p.slug===slug);
const cards=[
{id:'nigeria',tab:'October 1',title:'Happy birthday, Nigeria.',copy:'October 1 · Celebrating our independence, our people and what comes next.',video:'nigeria-independence.mp4',poster:'nigeria-independence-poster.jpg',path:'/nigerian-roots/',cta:'Our Nigerian roots'},
{id:'terranile',title:'Terranile',copy:'Technology, intelligence and infrastructure built for the long term.',image:'terranile-hero.webp',mobile:'terranile-hero-mobile.webp',width:1944,height:809,alt:'Conceptual titanium structure across a calm waterfront',path:'/company/',cta:'Our company'},
...['avan','helios','opex-intelli','avanbnb'].map(slug=>{const p=find(slug);return {id:p.slug,title:p.name,copy:p.summary,image:p.image,mobile:p.image.endsWith('.webp')?p.image.replace('.webp','-mobile.webp'):null,width:1672,height:941,alt:p.alt,path:p.path,website:p.website,cta:'Learn more'}})
];
return `<section class="panel-hero" aria-labelledby="hero-heading" data-panel-deck>
<div class="deck-heading"><h1 id="hero-heading">We build infrastructure for what comes next.</h1></div>
<div class="deck-viewport" role="region" aria-roledescription="carousel" aria-label="Terranile companies and research" data-deck-viewport>
  <div class="deck-track" data-deck-track>${cards.map((card,i)=>`<article class="deck-card" id="hero-${card.id}" role="group" aria-roledescription="slide" aria-label="${i+1} of ${cards.length}: ${card.title}" data-deck-card>
    <a class="deck-image-link" href="${card.path}" aria-label="Explore ${card.title}" tabindex="${i===0?'0':'-1'}">${card.video?`<video class="deck-video" data-deck-video data-video-src="/assets/${card.video}" poster="/assets/${card.poster}" muted loop playsinline preload="none" aria-label="Nigeria Independence Day celebration film"></video>`:`<img src="/assets/${card.image}" ${card.mobile?`srcset="/assets/${card.mobile} 900w, /assets/${card.image} ${card.width}w" sizes="(max-width:640px) calc(100vw - 32px), (min-width:1680px) 1400px, (min-width:1280px) 1200px, calc(100vw - 88px)"`:''} alt="${card.alt}" width="${card.width}" height="${card.height}" draggable="false" ${i===0?'fetchpriority="high"':'loading="lazy"'}>`}</a>
    <div class="deck-card-content"><div><h2>${card.title}</h2><p>${card.copy}</p></div><div class="deck-actions"><a href="${card.path}" tabindex="${i===0?'0':'-1'}">${card.cta}</a>${card.website?`<a href="${card.website}" target="_blank" rel="noopener noreferrer" tabindex="${i===0?'0':'-1'}">Open platform</a>`:''}</div></div>
  </article>`).join('')}</div>
</div>
<div class="deck-controls"><div class="deck-tabs" aria-label="Choose featured panel">${cards.map((card,i)=>`<button class="deck-tab ${i===0?'is-active':''}" type="button" data-deck-select="${i}" aria-pressed="${i===0?'true':'false'}" aria-controls="hero-${card.id}">${card.tab||card.title}<span class="deck-progress" aria-hidden="true"><span></span></span></button>`).join('')}</div><div class="deck-extra"><button type="button" class="deck-pause" data-deck-pause aria-pressed="false">Pause</button><a class="text-link" href="/projects/">Explore more</a></div></div>
<span class="sr-only" role="status" aria-live="polite" data-deck-status></span>
</section>
${capitalIntro}
<section class="section people-story"><figure class="reveal"><img src="/assets/construction-owner.jpg" sizes="(max-width:900px) 100vw, 55vw" alt="Two construction professionals reviewing plans at a building site" width="1408" height="768" loading="lazy"><figcaption class="mono">Illustrative partnership imagery / Real estate & real assets</figcaption></figure><div class="reveal"><span class="eyebrow">Real estate & real assets</span><h2>Built in partnership.<br>Connected by infrastructure.</h2><p>Terranile works with developers, landowners and industry partners across real estate and real assets, connecting physical projects with technology, distribution, investment access and transaction infrastructure.</p><a class="text-link" href="/projects/real-assets/">Explore real estate partnerships</a></div></section>
<section class="section selected-perspectives"><div class="section-head"><div><span class="eyebrow">News / Perspectives / Announcements</span><h2>Ideas and updates.</h2></div><a class="text-link" href="/news/">Explore the newsroom</a></div><div class="editorial-list"><a class="editorial-row" href="/perspectives/trust-is-infrastructure/"><span class="mono">Infrastructure</span><h3>Trust is infrastructure.</h3><span>Read perspective</span></a><a class="editorial-row" href="/perspectives/research-beyond-the-application/"><span class="mono">Research</span><h3>Research beyond the application.</h3><span>Read perspective</span></a></div></section>${ecosystem(projects)}`;
}
